version: '3.8'

services:
  database-lwg:
    container_name: database-lwg
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MARIADB_DATABASE: lwg_db
    ports:
      - '3306:3306'
  php-lwg:
    container_name: php-lwg
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/app
    depends_on:
      - database-lwg
  nginx-lwg:
    container_name: nginx-lwg
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-lwg
      - database-lwg
